spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/okbut?charSet=utf-8
    username: okbut
    password: okpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    encoding:
      force-response: true
