version: "3.8"

services:
  testdb:
    container_name: corporate-library-testdb
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: okbut
      POSTGRES_USER: okbut
      POSTGRES_PASSWORD: okpass
    restart: always
    ports:
      - "5432:5432"
  apiserver:
    container_name: corporate-library-apiserver
    build:
      context: ..
      dockerfile: Dockerfile
    image: markruler/corporate-library-apiserver:latest
    depends_on:
      - testdb
    restart: unless-stopped
    ports:
      - "8080:8080"
